<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ModInspect</AssemblyName>
    <StartupObject>ModInspect</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>..\..\BepInEx\core\Mono.Cecil.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
